"""Generate smaller copies of every photo, plus a manifest the site reads.

Why: a phone shows a photo in a slot ~400px wide, but was downloading the full
2560px file. With several sizes available the browser picks the smallest one
that still looks sharp on that screen — same visible quality, far less data.

Run this after adding new photos to /images:

    python tools/build-image-variants.py

It writes:
  images/<name>-800.jpeg, images/<name>-1600.jpeg   (only when smaller than the source)
  js/image-variants.js                              (which sizes exist, for main.js)

Photos without an entry in the manifest simply load normally, so the site never
breaks if this script has not been run yet.
"""
import json
import os
import re
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(ROOT, "images")
MANIFEST = os.path.join(ROOT, "js", "image-variants.js")

WIDTHS = [800, 1600]          # variants to produce
QUALITY = 84                   # slightly below the master; these are shown smaller
VARIANT_RE = re.compile(r"-(\d+)\.jpe?g$", re.I)


def is_variant(name):
    return bool(VARIANT_RE.search(name))


def main():
    manifest = {}
    made = skipped = 0

    for fn in sorted(os.listdir(IMG_DIR)):
        if not fn.lower().endswith((".jpg", ".jpeg")) or is_variant(fn):
            continue

        path = os.path.join(IMG_DIR, fn)
        rel = "images/" + fn
        with Image.open(path) as im:
            im.load()
            w, h = im.size
            im = im.convert("RGB")

            candidates = []
            for target in WIDTHS:
                if target >= w:
                    continue           # never upscale
                out_name = f"{os.path.splitext(fn)[0]}-{target}.jpeg"
                out_path = os.path.join(IMG_DIR, out_name)
                if not os.path.exists(out_path):
                    resized = im.resize(
                        (target, round(h * target / w)), Image.LANCZOS)
                    resized.save(out_path, "JPEG", quality=QUALITY,
                                 optimize=True, progressive=True,
                                 subsampling="4:2:0")
                    made += 1
                else:
                    skipped += 1
                candidates.append([target, "images/" + out_name])

            if candidates:                       # plus the full-size master
                candidates.append([w, rel])
                manifest[rel] = candidates

    with open(MANIFEST, "w", encoding="utf8") as f:
        f.write("/* Generated by tools/build-image-variants.py — do not edit by hand.\n"
                "   Maps each photo to the widths available, so the browser can pick\n"
                "   the smallest file that still looks sharp on the visitor's screen. */\n")
        f.write("window.imageVariants = ")
        json.dump(manifest, f, indent=0, ensure_ascii=False)
        f.write(";\n")

    total = sum(os.path.getsize(os.path.join(IMG_DIR, f))
                for f in os.listdir(IMG_DIR) if f.lower().endswith((".jpg", ".jpeg")))
    print(f"variants written: {made} new, {skipped} already present")
    print(f"photos with variants: {len(manifest)}")
    print(f"images/ total now: {total/1048576:.1f} MB")


if __name__ == "__main__":
    main()
