"""Generate smaller copies of every photo, plus a manifest the site reads.

Why: a phone shows a photo in a slot ~400px wide, but was downloading the full
2560px file. With several sizes available the browser picks the smallest one
that still looks sharp on that screen — same visible quality, far less data.

Run this after adding new photos to /images:

    python tools/build-image-variants.py

It writes:
  images/<name>-800.jpeg, images/<name>-1600.jpeg   (only when smaller than the source)
  js/image-variants.js   which sizes exist (imageVariants), each photo's exact
                         shape (imageRatios) and a characteristic colour
                         (imageTones, used to tint the Chroma pages)

Photos without an entry in the manifest simply load normally, so the site never
breaks if this script has not been run yet.
"""
import colorsys
import json
import os
import re
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(ROOT, "images")
MANIFEST = os.path.join(ROOT, "js", "image-variants.js")

WIDTHS = [800, 1600]          # variants to produce
QUALITY = 84                   # slightly below the master; these are shown smaller
VARIANT_RE = re.compile(r"-(\d+)\.jpe?g$", re.I)


def is_variant(name):
    return bool(VARIANT_RE.search(name))


def is_skipped(name):
    # the link-preview card is only ever fetched by WhatsApp/Instagram etc.
    return name.lower().startswith("share")


def tone(im):
    """The colour that characterises a photo: of its main colours, the one that
    is both fairly saturated and covers a real part of the frame (a plain
    average turns most colour photos into mud)."""
    s = im.copy()
    s.thumbnail((80, 80))
    q = s.quantize(colors=8, method=Image.Quantize.MEDIANCUT)
    pal, total = q.getpalette(), s.size[0] * s.size[1]
    best, score = None, -1.0
    for count, idx in q.getcolors():
        r, g, b = pal[idx * 3: idx * 3 + 3]
        _, light, sat = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
        if light < 0.12 or light > 0.92:
            continue
        sc = (count / total) * (0.25 + sat)
        if sc > score:
            best, score = (r, g, b), sc
    if best is None:
        best = s.resize((1, 1), Image.LANCZOS).getpixel((0, 0))
    return "#%02x%02x%02x" % best


def main():
    manifest, ratios, tones = {}, {}, {}
    made = skipped = 0

    for fn in sorted(os.listdir(IMG_DIR)):
        if not fn.lower().endswith((".jpg", ".jpeg")) or is_variant(fn) or is_skipped(fn):
            continue

        path = os.path.join(IMG_DIR, fn)
        rel = "images/" + fn
        with Image.open(path) as im:
            im.load()
            w, h = im.size
            im = im.convert("RGB")
            ratios[rel] = round(w / h, 4)
            tones[rel] = tone(im)

            candidates = []
            for target in WIDTHS:
                if target >= w:
                    continue           # never upscale
                out_name = f"{os.path.splitext(fn)[0]}-{target}.jpeg"
                out_path = os.path.join(IMG_DIR, out_name)
                if not os.path.exists(out_path):
                    resized = im.resize(
                        (target, round(h * target / w)), Image.LANCZOS)
                    resized.save(out_path, "JPEG", quality=QUALITY,
                                 optimize=True, progressive=True,
                                 subsampling="4:2:0")
                    made += 1
                else:
                    skipped += 1
                candidates.append([target, "images/" + out_name])

            if candidates:                       # plus the full-size master
                candidates.append([w, rel])
                manifest[rel] = candidates

    with open(MANIFEST, "w", encoding="utf8") as f:
        f.write("/* Generated by tools/build-image-variants.py — do not edit by hand.\n"
                "   Maps each photo to the widths available, so the browser can pick\n"
                "   the smallest file that still looks sharp on the visitor's screen. */\n")
        f.write("window.imageVariants = ")
        json.dump(manifest, f, indent=0, ensure_ascii=False)
        f.write(";\n")
        f.write("window.imageRatios = ")       # exact width ÷ height of each master
        json.dump(ratios, f, ensure_ascii=False)
        f.write(";\n")
        f.write("window.imageTones = ")        # characteristic colour of each photo
        json.dump(tones, f, ensure_ascii=False)
        f.write(";\n")

    total = sum(os.path.getsize(os.path.join(IMG_DIR, f))
                for f in os.listdir(IMG_DIR) if f.lower().endswith((".jpg", ".jpeg")))
    print(f"variants written: {made} new, {skipped} already present")
    print(f"photos with variants: {len(manifest)}")
    print(f"images/ total now: {total/1048576:.1f} MB")


if __name__ == "__main__":
    main()
